<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Core\RouteException;
use Neoan3\Frame\Neoan;

class DevTo extends Neoan
{


    function postDevTo(array $body)
    {

        // check token
        $jwt = Stateless::restrict();
        // get dev.to api key
        try{
            $credentials = getCredentials();
            $apiKey = $this->getApiKey($credentials);

            // prepare content

            switch ($body['event']){
                case 'created': break;
                case 'updated': break;
                case 'deleted': break;
            }
        } catch (\Exception $e){
            throw new RouteException('Unable to execute dev.to plugin',500);
        }
        echo ['webhook' => 'received'];
    }
    function getApiKey($credentials){
        if(!isset($credentials['devToApiKey'])){
            throw new \Exception('Key not set');
        }
        return $credentials['devToApiKey'];
    }


}
